language: android
jdk: oraclejdk8

android:
  components:
    # Android SDK Tools
    - tools 26.0.2
    - platform-tools 25.0.6

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

    before_install:
      - mkdir "$ANDROID_HOME/licenses" || true
      - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
      - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"